# Generated by Django 4.0.5 on 2022-06-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_remove_item_sub_category_id_sub_cat_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_of_subcat', to='appone.sub_category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='sub_cat_item',
        ),
    ]
