# Generated by Django 4.0.5 on 2022-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_item_sub_cat_id_delete_sub_cat_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AddField(
            model_name='sub_category',
            name='sub_category_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='type_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
