# Generated by Django 4.0.5 on 2022-07-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appone', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev', to=settings.AUTH_USER_MODEL),
        ),
    ]
