# Generated by Django 4.0.5 on 2022-07-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_review_user_id_alter_review_item_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
