# Generated by Django 4.0.5 on 2022-07-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0010_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
