# Generated by Django 4.0.5 on 2022-07-13 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appone', '0011_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revw', to='appone.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
