# Generated by Django 4.0.5 on 2022-07-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0013_alter_cart_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item_id',
            new_name='item_trend_id',
        ),
    ]
