# Generated by Django 4.0.5 on 2022-07-14 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appone', '0014_rename_item_id_cart_item_trend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_trend_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appone.item_trend'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
