# Generated by Django 4.0.5 on 2022-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0018_details_item_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_detail',
            name='details_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
