# Generated by Django 4.0.5 on 2022-07-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0019_item_detail_details_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='details_desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='details_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item_detail',
            name='details_info',
            field=models.CharField(max_length=100),
        ),
    ]
