# Generated by Django 4.0.5 on 2022-07-31 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0021_alter_item_detail_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_detail',
            name='detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itm_detail', to='appone.details'),
        ),
    ]
